channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch>=1.10
  - cudatoolkit=11.3
  - transformers=4.16.2
  - datasets>=1.18
  - rdflib
  - scipy
  - scikit-learn
