channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
  - plotly
dependencies:
  - defaults::python=3.9
  - defaults::pip
  - pytorch::pytorch=1.10
  - nvidia::cudatoolkit=11.3
  - conda-forge::transformers=4.15
  - conda-forge::datasets>=2
  - conda-forge::rdflib
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - conda-forge::seqeval
  - plotly::plotly
  - pip:
      - tokenizers>=0.11
